## EDA-2

### Exploration

In [91]:
import pandas as pd
import numpy as np

df = pd.read_csv("adult_with_headers.csv")

In [92]:
df.head(5)

,age,workclass,fnlwgt,education,education_num,marital_status,occupation,relationship,race,sex,capital_gain,capital_loss,hours_per_week,native_country,income
0,39,State-gov,77516,Bachelors,13,Never-married,Adm-clerical,Not-in-family,White,Male,2174,0,40,United-States,<=50K
1,50,Self-emp-not-inc,83311,Bachelors,13,Married-civ-spouse,Exec-managerial,Husband,White,Male,0,0,13,United-States,<=50K
2,38,Private,215646,HS-grad,9,Divorced,Handlers-cleaners,Not-in-family,White,Male,0,0,40,United-States,<=50K
3,53,Private,234721,11th,7,Married-civ-spouse,Handlers-cleaners,Husband,Black,Male,0,0,40,United-States,<=50K
4,28,Private,338409,Bachelors,13,Married-civ-spouse,Prof-specialty,Wife,Black,Female,0,0,40,Cuba,<=50K

In [93]:
print(df.shape)

(32561, 15)

In [94]:
print(df.info())

<class 'pandas.DataFrame'>
RangeIndex: 32561 entries, 0 to 32560
Data columns (total 15 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   age             32561 non-null  int64
 1   workclass       32561 non-null  str
 2   fnlwgt          32561 non-null  int64
 3   education       32561 non-null  str
 4   education_num   32561 non-null  int64
 5   marital_status  32561 non-null  str
 6   occupation      32561 non-null  str
 7   relationship    32561 non-null  str
 8   race            32561 non-null  str
 9   sex             32561 non-null  str
 10  capital_gain    32561 non-null  int64
 11  capital_loss    32561 non-null  int64
 12  hours_per_week  32561 non-null  int64
 13  native_country  32561 non-null  str
 14  income          32561 non-null  str
dtypes: int64(6), str(9)
memory usage: 6.5 MB
None

In [95]:
df.describe(include='all')

,age,workclass,fnlwgt,education,education_num,marital_status,occupation,relationship,race,sex,capital_gain,capital_loss,hours_per_week,native_country,income
count,32561.000000,32561,3.256100e+04,32561,32561.000000,32561,32561,32561,32561,32561,32561.000000,32561.000000,32561.000000,32561,32561
unique,NaN,9,NaN,16,NaN,7,15,6,5,2,NaN,NaN,NaN,42,2
top,NaN,Private,NaN,HS-grad,NaN,Married-civ-spouse,Prof-specialty,Husband,White,Male,NaN,NaN,NaN,United-States,<=50K
freq,NaN,22696,NaN,10501,NaN,14976,4140,13193,27816,21790,NaN,NaN,NaN,29170,24720
mean,38.581647,NaN,1.897784e+05,NaN,10.080679,NaN,NaN,NaN,NaN,NaN,1077.648844,87.303830,40.437456,NaN,NaN
std,13.640433,NaN,1.055500e+05,NaN,2.572720,NaN,NaN,NaN,NaN,NaN,7385.292085,402.960219,12.347429,NaN,NaN
min,17.000000,NaN,1.228500e+04,NaN,1.000000,NaN,NaN,NaN,NaN,NaN,0.000000,0.000000,1.000000,NaN,NaN
25%,28.000000,NaN,1.178270e+05,NaN,9.000000,NaN,NaN,NaN,NaN,NaN,0.000000,0.000000,40.000000,NaN,NaN
50%,37.000000,NaN,1.783560e+05,NaN,10.000000,NaN,NaN,NaN,NaN,NaN,0.000000,0.000000,40.000000,NaN,NaN
75%,48.000000,NaN,2.370510e+05,NaN,12.000000,NaN,NaN,NaN,NaN,NaN,0.000000,0.000000,45.000000,NaN,NaN
max,90.000000,NaN,1.484705e+06,NaN,16.000000,NaN,NaN,NaN,NaN,NaN,99999.000000,4356.000000,99.000000,NaN,NaN

In [96]:
#Replacing missing values with NaN
df.replace("?", np.nan, inplace=True)
df.replace(" ?", np.nan, inplace=True)

,age,workclass,fnlwgt,education,education_num,marital_status,occupation,relationship,race,sex,capital_gain,capital_loss,hours_per_week,native_country,income
0,39,State-gov,77516,Bachelors,13,Never-married,Adm-clerical,Not-in-family,White,Male,2174,0,40,United-States,<=50K
1,50,Self-emp-not-inc,83311,Bachelors,13,Married-civ-spouse,Exec-managerial,Husband,White,Male,0,0,13,United-States,<=50K
2,38,Private,215646,HS-grad,9,Divorced,Handlers-cleaners,Not-in-family,White,Male,0,0,40,United-States,<=50K
3,53,Private,234721,11th,7,Married-civ-spouse,Handlers-cleaners,Husband,Black,Male,0,0,40,United-States,<=50K
4,28,Private,338409,Bachelors,13,Married-civ-spouse,Prof-specialty,Wife,Black,Female,0,0,40,Cuba,<=50K
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
32556,27,Private,257302,Assoc-acdm,12,Married-civ-spouse,Tech-support,Wife,White,Female,0,0,38,United-States,<=50K
32557,40,Private,154374,HS-grad,9,Married-civ-spouse,Machine-op-inspct,Husband,White,Male,0,0,40,United-States,>50K
32558,58,Private,151910,HS-grad,9,Widowed,Adm-clerical,Unmarried,White,Female,0,0,40,United-States,<=50K
32559,22,Private,201490,HS-grad,9,Never-married,Adm-clerical,Own-child,White,Male,0,0,20,United-States,<=50K
32560,52,Self-emp-inc,287927,HS-grad,9,Married-civ-spouse,Exec-managerial,Wife,White,Female,15024,0,40,United-States,>50K

In [97]:
print(df.isnull().sum())

age                  0
workclass         1836
fnlwgt               0
education            0
education_num        0
marital_status       0
occupation        1843
relationship         0
race                 0
sex                  0
capital_gain         0
capital_loss         0
hours_per_week       0
native_country     583
income               0
dtype: int64

### Missing Value Handling

In [98]:
df.dtypes
#No object datatype beacuse in Python 3.14.6 it is changed to str datatype.

age               int64
workclass           str
fnlwgt            int64
education           str
education_num     int64
marital_status      str
occupation          str
relationship        str
race                str
sex                 str
capital_gain      int64
capital_loss      int64
hours_per_week    int64
native_country      str
income              str
dtype: object

In [99]:
#Replacing missing categorical values with mode and numeric values with median.
for col in df.columns:
    if str(df[col].dtype) == 'str':
        df[col] = df[col].fillna(df[col].mode()[0])
    else:
        df[col] = df[col].fillna(df[col].median())

print(df.isnull().sum().sum())

0

### Scaling

In [100]:
from sklearn.preprocessing import StandardScaler, MinMaxScaler

num_cols = df.select_dtypes(include=np.number).columns

standard_df = df.copy()
minmax_df = df.copy()

standard_df[num_cols] = StandardScaler().fit_transform(standard_df[num_cols])
minmax_df[num_cols] = MinMaxScaler().fit_transform(minmax_df[num_cols])

In [101]:
standard_df[num_cols].head()

,age,fnlwgt,education_num,capital_gain,capital_loss,hours_per_week
0,0.030671,-1.063611,1.134739,0.148453,-0.21666,-0.035429
1,0.837109,-1.008707,1.134739,-0.145920,-0.21666,-2.222153
2,-0.042642,0.245079,-0.420060,-0.145920,-0.21666,-0.035429
3,1.057047,0.425801,-1.197459,-0.145920,-0.21666,-0.035429
4,-0.775768,1.408176,1.134739,-0.145920,-0.21666,-0.035429

In [102]:
minmax_df[num_cols].head()

,age,fnlwgt,education_num,capital_gain,capital_loss,hours_per_week
0,0.301370,0.044302,0.800000,0.02174,0.0,0.397959
1,0.452055,0.048238,0.800000,0.00000,0.0,0.122449
2,0.287671,0.138113,0.533333,0.00000,0.0,0.397959
3,0.493151,0.151068,0.400000,0.00000,0.0,0.397959
4,0.150685,0.221488,0.800000,0.00000,0.0,0.397959

Standard Scaling: Best for algorithms such as Logistic Regression, SVM, and PCA because it centers data around zero with unit variance.

Min-Max Scaling: Preferred for Neural Networks and distance-based algorithms when values should remain within a fixed range (0 to 1).

### Encoding

In [103]:
#Seeing how many unique categories in each categorical column
df.select_dtypes(include='str').nunique()

workclass          8
education         16
marital_status     7
occupation        14
relationship       6
race               5
sex                2
native_country    41
income             2
dtype: int64

In [104]:
from sklearn.preprocessing import LabelEncoder

sample_df = df.copy()

sc = [] #Small categorical columns for One-Hot Encoding
lc = [] #Large categorical columns for Label Encoding

for col in sample_df.columns:
    if str(sample_df[col].dtype) == 'str':
        if sample_df[col].nunique() < 5:
            sc.append(col)
        else:
            lc.append(col)

print("Columns for One-Hot Encoding:", sc)
print("Columns for Label Encoding:", lc)

Columns for One-Hot Encoding: ['sex', 'income']
Columns for Label Encoding: ['workclass', 'education', 'marital_status', 'occupation', 'relationship', 'race', 'native_country']

In [105]:
# One-Hot Encoding
encoded_df = pd.get_dummies(sample_df, columns=sc)

# Label Encoding
le = LabelEncoder()
for col in lc:
    encoded_df[col] = le.fit_transform(encoded_df[col])

encoded_df.head()

,age,workclass,fnlwgt,education,education_num,marital_status,occupation,relationship,race,capital_gain,capital_loss,hours_per_week,native_country,sex_ Female,sex_ Male,income_ <=50K,income_ >50K
0,39,6,77516,9,13,4,0,1,4,2174,0,40,38,False,True,True,False
1,50,5,83311,9,13,2,3,0,4,0,0,13,38,False,True,True,False
2,38,3,215646,11,9,0,5,1,4,0,0,40,38,False,True,True,False
3,53,3,234721,1,7,2,5,0,2,0,0,40,38,False,True,True,False
4,28,3,338409,9,13,2,9,5,2,0,0,40,4,True,False,True,False

**One-Hot Encoding**
- No false ordering
- Increases dimensions

**Label Encoding**
- Memory efficient
- Can introduce artificial ordering

### Feature Engineering

In [106]:
df.columns

Index(['age', 'workclass', 'fnlwgt', 'education', 'education_num',
       'marital_status', 'occupation', 'relationship', 'race', 'sex',
       'capital_gain', 'capital_loss', 'hours_per_week', 'native_country',
       'income'],
      dtype='str')

In [107]:
#Creating two additional features
df['capital_total'] = df['capital_gain'] + df['capital_loss']
df['has_capital'] = (df['capital_total'] > 0).astype(int)

df[['capital_total', 'has_capital']].head()

   capital_total  has_capital
0           2174            1
1              0            0
2              0            0
3              0            0
4              0            0

In [120]:
#Checking how much columns are skewed
print(df.skew(numeric_only=True))

age                  0.558743
fnlwgt               1.446980
education_num       -0.311676
capital_gain        11.953848
capital_loss         4.594629
hours_per_week       0.227643
capital_total       11.927101
has_capital          2.201275
log_capital_gain     3.096144
dtype: float64

In [122]:
df['capital_gain'].head(5)

0    2174
1       0
2       0
3       0
4       0
Name: capital_gain, dtype: int64

In [ ]:
#Transforming capital gain column using log transformation
df['log_capital_gain'] = np.log1p(df['capital_gain'])

In [111]:
df['log_capital_gain'].head()

0    7.684784
1    0.000000
2    0.000000
3    0.000000
4    0.000000
Name: log_capital_gain, dtype: float64

In [112]:
print("Before transformation:", df['capital_gain'].skew())
print("After transformation :", df['log_capital_gain'].skew())

Before transformation: 11.953847687699804
After transformation : 3.096143524467517

### Outlier Removal using Isolation Forest

In [116]:
from sklearn.ensemble import IsolationForest

iso = IsolationForest(contamination=0.05, random_state=42)
pred = iso.fit_predict(df[num_cols])
#1 is not outlier adn -1 is a outlier
clean_df = df[pred == 1]
print('Original:', len(df))
print('After removing outliers:', len(clean_df))

Original: 32561
After removing outliers: 30933

Outliers may distort model training, increase variance, and reduce prediction accuracy.

### PPS Score and Correlation

In [118]:
import ppscore as pps
import warnings
warnings.filterwarnings("ignore")

pps_matrix = pps.matrix(clean_df)
pps_matrix.head()

,x,y,ppscore,case,is_valid_score,metric,baseline_score,model_score,model
0,age,age,1.000000,predict_itself,True,NaN,0.000000,1.000000,None
1,age,workclass,0.000000,classification,True,weighted F1,0.652845,0.652648,DecisionTreeClassifier()
2,age,fnlwgt,0.000000,regression,True,mean absolute error,75762.580600,76675.641971,DecisionTreeRegressor()
3,age,education,0.054854,classification,True,weighted F1,0.193400,0.237645,DecisionTreeClassifier()
4,age,education_num,0.000000,regression,True,mean absolute error,1.837800,1.876019,DecisionTreeRegressor()

In [119]:
corr = clean_df[num_cols].corr()
corr

,age,fnlwgt,education_num,capital_gain,capital_loss,hours_per_week
age,1.000000,-0.079026,0.035963,0.093410,0.029835,0.094233
fnlwgt,-0.079026,1.000000,-0.039355,-0.012993,-0.011045,-0.021354
education_num,0.035963,-0.039355,1.000000,0.130080,0.045779,0.134755
capital_gain,0.093410,-0.012993,0.130080,1.000000,-0.032021,0.082962
capital_loss,0.029835,-0.011045,0.045779,-0.032021,1.000000,0.010101
hours_per_week,0.094233,-0.021354,0.134755,0.082962,0.010101,1.000000

**Comparison**

- Correlation measures only linear relationships between numeric variables.
- PPS detects linear and non-linear predictive relationships and also works with categorical variables.
- PPS is generally more informative for feature selection in mixed datasets.